import { type Municipio, Region } from "../types/index";

/**
 * Los 135 partidos de la Provincia de Buenos Aires.
 * Códigos INDEC de 6 dígitos (provincia 06 + código de partido).
 * Los 13 municipios piloto tienen datos completos (población Censo 2022, superficie, URL oficial).
 * El resto tiene datos mínimos que se irán completando.
 */
export const MUNICIPIOS: Municipio[] = [
  // =====================================================
  // 13 MUNICIPIOS PILOTO (datos completos)
  // =====================================================
  {
    id: "060056",
    nombre: "Bahía Blanca",
    partido: "Bahía Blanca",
    urlOficial: "https://www.bahiablanca.gob.ar",
    poblacion: 335190,
    superficieKm2: 2300,
    densidad: 145.7,
    region: Region.INTERIOR,
    esPiloto: true,
  },
  {
    id: "060357",
    nombre: "General Pueyrredón",
    partido: "General Pueyrredón",
    urlOficial: "https://www.mardelplata.gob.ar",
    poblacion: 656456,
    superficieKm2: 1460,
    densidad: 449.6,
    region: Region.COSTA_ATLANTICA,
    esPiloto: true,
  },
  {
    id: "060791",
    nombre: "Tandil",
    partido: "Tandil",
    urlOficial: "https://www.tandil.gov.ar",
    poblacion: 137218,
    superficieKm2: 4935,
    densidad: 27.8,
    region: Region.INTERIOR,
    esPiloto: true,
  },
  {
    id: "060861",
    nombre: "Vicente López",
    partido: "Vicente López",
    urlOficial: "https://www.vicentelopez.gov.ar",
    poblacion: 274082,
    superficieKm2: 33,
    densidad: 8305.5,
    region: Region.CONURBANO_NORTE,
    esPiloto: true,
  },
  {
    id: "060735",
    nombre: "San Isidro",
    partido: "San Isidro",
    urlOficial: "https://www.sanisidro.gob.ar",
    poblacion: 295210,
    superficieKm2: 48,
    densidad: 6150.2,
    region: Region.CONURBANO_NORTE,
    esPiloto: true,
  },
  {
    id: "060441",
    nombre: "La Plata",
    partido: "La Plata",
    urlOficial: "https://www.laplata.gob.ar",
    poblacion: 740369,
    superficieKm2: 926,
    densidad: 799.5,
    region: Region.AMBA,
    esPiloto: true,
  },
  {
    id: "060882",
    nombre: "Zárate",
    partido: "Zárate",
    urlOficial: "https://www.zarate.gob.ar",
    poblacion: 120318,
    superficieKm2: 1202,
    densidad: 100.1,
    region: Region.INTERIOR,
    esPiloto: true,
  },
  {
    id: "060490",
    nombre: "Luján",
    partido: "Luján",
    urlOficial: "https://www.lujan.gob.ar",
    poblacion: 116480,
    superficieKm2: 800,
    densidad: 145.6,
    region: Region.INTERIOR,
    esPiloto: true,
  },
  {
    id: "060042",
    nombre: "Ayacucho",
    partido: "Ayacucho",
    urlOficial: "https://www.ayacucho.gob.ar",
    poblacion: 22684,
    superficieKm2: 6785,
    densidad: 3.3,
    region: Region.INTERIOR,
    esPiloto: true,
  },
  {
    id: "060476",
    nombre: "Lobería",
    partido: "Lobería",
    urlOficial: "https://www.loberia.gob.ar",
    poblacion: 18926,
    superficieKm2: 4755,
    densidad: 4.0,
    region: Region.INTERIOR,
    esPiloto: true,
  },
  {
    id: "060049",
    nombre: "Azul",
    partido: "Azul",
    urlOficial: "https://www.azul.gob.ar",
    poblacion: 69698,
    superficieKm2: 6615,
    densidad: 10.5,
    region: Region.INTERIOR,
    esPiloto: true,
  },
  {
    id: "060105",
    nombre: "Bragado",
    partido: "Bragado",
    urlOficial: "https://www.bragado.gov.ar",
    poblacion: 43347,
    superficieKm2: 2230,
    densidad: 19.4,
    region: Region.INTERIOR,
    esPiloto: true,
  },
  {
    id: "060567",
    nombre: "Necochea",
    partido: "Necochea",
    urlOficial: "https://www.necochea.gob.ar",
    poblacion: 98001,
    superficieKm2: 4455,
    densidad: 22.0,
    region: Region.COSTA_ATLANTICA,
    esPiloto: true,
  },

  // =====================================================
  // RESTANTES 122 PARTIDOS (datos mínimos)
  // =====================================================
  { id: "060007", nombre: "Adolfo Alsina", partido: "Adolfo Alsina", urlOficial: "https://www.adolfoalsina.gov.ar/", poblacion: 17072, superficieKm2: 5875, densidad: 2.9, region: Region.INTERIOR, esPiloto: false },
  { id: "060014", nombre: "Adolfo Gonzales Chaves", partido: "Adolfo Gonzales Chaves", urlOficial: null, poblacion: 12047, superficieKm2: 3780, densidad: 3.2, region: Region.INTERIOR, esPiloto: false },
  { id: "060021", nombre: "Alberti", partido: "Alberti", urlOficial: "https://alberti.gov.ar/", poblacion: 11990, superficieKm2: 1130, densidad: 10.6, region: Region.INTERIOR, esPiloto: false },
  { id: "060028", nombre: "Almirante Brown", partido: "Almirante Brown", urlOficial: null, poblacion: 597694, superficieKm2: 122, densidad: 4899.1, region: Region.CONURBANO_SUR, esPiloto: false },
  { id: "060035", nombre: "Arrecifes", partido: "Arrecifes", urlOficial: "https://arrecifes.gob.ar/", poblacion: 32291, superficieKm2: 1100, densidad: 29.4, region: Region.INTERIOR, esPiloto: false },
  { id: "060063", nombre: "Avellaneda", partido: "Avellaneda", urlOficial: "https://avellaneda.gob.ar/", poblacion: 354697, superficieKm2: 55, densidad: 6449.0, region: Region.CONURBANO_SUR, esPiloto: false },
  { id: "060070", nombre: "Balcarce", partido: "Balcarce", urlOficial: "https://balcarce.gob.ar/", poblacion: 47713, superficieKm2: 4120, densidad: 11.6, region: Region.INTERIOR, esPiloto: false },
  { id: "060077", nombre: "Baradero", partido: "Baradero", urlOficial: "https://baradero.gob.ar/", poblacion: 34903, superficieKm2: 1514, densidad: 23.1, region: Region.INTERIOR, esPiloto: false },
  { id: "060084", nombre: "Benito Juárez", partido: "Benito Juárez", urlOficial: "https://benitojuarez.gov.ar/", poblacion: 21730, superficieKm2: 5285, densidad: 4.1, region: Region.INTERIOR, esPiloto: false },
  { id: "060091", nombre: "Berazategui", partido: "Berazategui", urlOficial: "https://berazategui.gob.ar/", poblacion: 330073, superficieKm2: 188, densidad: 1755.7, region: Region.CONURBANO_SUR, esPiloto: false },
  { id: "060098", nombre: "Berisso", partido: "Berisso", urlOficial: "https://www.berisso.gob.ar/", poblacion: 95648, superficieKm2: 135, densidad: 708.5, region: Region.AMBA, esPiloto: false },
  { id: "060112", nombre: "Brandsen", partido: "Brandsen", urlOficial: "https://www.brandsen.gob.ar/", poblacion: 32088, superficieKm2: 1126, densidad: 28.5, region: Region.INTERIOR, esPiloto: false },
  { id: "060119", nombre: "Campana", partido: "Campana", urlOficial: "https://www.campana.gob.ar/", poblacion: 105823, superficieKm2: 982, densidad: 107.8, region: Region.INTERIOR, esPiloto: false },
  { id: "060126", nombre: "Cañuelas", partido: "Cañuelas", urlOficial: "https://www.canuelas.gob.ar/", poblacion: 58322, superficieKm2: 1203, densidad: 48.5, region: Region.INTERIOR, esPiloto: false },
  { id: "060134", nombre: "Capitán Sarmiento", partido: "Capitán Sarmiento", urlOficial: "https://capitansarmiento.gob.ar/", poblacion: 16596, superficieKm2: 613, densidad: 27.1, region: Region.INTERIOR, esPiloto: false },
  { id: "060140", nombre: "Carlos Casares", partido: "Carlos Casares", urlOficial: "https://casares.gob.ar/", poblacion: 23454, superficieKm2: 2446, densidad: 9.6, region: Region.INTERIOR, esPiloto: false },
  { id: "060147", nombre: "Carlos Tejedor", partido: "Carlos Tejedor", urlOficial: "https://carlostejedor.gob.ar/", poblacion: 12038, superficieKm2: 3940, densidad: 3.1, region: Region.INTERIOR, esPiloto: false },
  { id: "060154", nombre: "Carmen de Areco", partido: "Carmen de Areco", urlOficial: "https://carmendeareco.gob.ar/", poblacion: 15738, superficieKm2: 1080, densidad: 14.6, region: Region.INTERIOR, esPiloto: false },
  { id: "060161", nombre: "Castelli", partido: "Castelli", urlOficial: "https://www.castelli.gob.ar/", poblacion: 8205, superficieKm2: 2100, densidad: 3.9, region: Region.INTERIOR, esPiloto: false },
  { id: "060168", nombre: "Colón", partido: "Colón", urlOficial: "https://colon.gov.ar/", poblacion: 26868, superficieKm2: 1010, densidad: 26.6, region: Region.INTERIOR, esPiloto: false },
  { id: "060175", nombre: "Coronel de Marina Leonardo Rosales", partido: "Coronel de Marina Leonardo Rosales", urlOficial: null, poblacion: 64799, superficieKm2: 1312, densidad: 49.4, region: Region.INTERIOR, esPiloto: false },
  { id: "060182", nombre: "Coronel Dorrego", partido: "Coronel Dorrego", urlOficial: "https://dorrego.gob.ar/mun/direcciones/mcd/index.php", poblacion: 16395, superficieKm2: 5818, densidad: 2.8, region: Region.INTERIOR, esPiloto: false },
  { id: "060189", nombre: "Coronel Pringles", partido: "Coronel Pringles", urlOficial: "https://www.coronelpringles.gov.ar/", poblacion: 24016, superficieKm2: 5245, densidad: 4.6, region: Region.INTERIOR, esPiloto: false },
  { id: "060196", nombre: "Coronel Suárez", partido: "Coronel Suárez", urlOficial: "https://www.coronelsuarez.gob.ar/", poblacion: 40407, superficieKm2: 5985, densidad: 6.8, region: Region.INTERIOR, esPiloto: false },
  { id: "060203", nombre: "Chacabuco", partido: "Chacabuco", urlOficial: "https://chacabuco.gob.ar/", poblacion: 52355, superficieKm2: 2440, densidad: 21.5, region: Region.INTERIOR, esPiloto: false },
  { id: "060210", nombre: "Chascomús", partido: "Chascomús", urlOficial: "https://www.chascomus.com.ar/", poblacion: 42677, superficieKm2: 4225, densidad: 10.1, region: Region.INTERIOR, esPiloto: false },
  { id: "060217", nombre: "Chivilcoy", partido: "Chivilcoy", urlOficial: "https://chivilcoy.gov.ar/", poblacion: 68638, superficieKm2: 2075, densidad: 33.1, region: Region.INTERIOR, esPiloto: false },
  { id: "060224", nombre: "Daireaux", partido: "Daireaux", urlOficial: "https://daireaux.gob.ar/", poblacion: 17052, superficieKm2: 3668, densidad: 4.6, region: Region.INTERIOR, esPiloto: false },
  { id: "060231", nombre: "Dolores", partido: "Dolores", urlOficial: "https://dolores.gob.ar/", poblacion: 28783, superficieKm2: 1980, densidad: 14.5, region: Region.INTERIOR, esPiloto: false },
  { id: "060238", nombre: "Ensenada", partido: "Ensenada", urlOficial: "https://www.ensenada.gov.ar/", poblacion: 60590, superficieKm2: 101, densidad: 599.9, region: Region.AMBA, esPiloto: false },
  { id: "060245", nombre: "Escobar", partido: "Escobar", urlOficial: "https://www.escobar.gob.ar/", poblacion: 233560, superficieKm2: 277, densidad: 843.0, region: Region.CONURBANO_NORTE, esPiloto: false },
  { id: "060252", nombre: "Esteban Echeverría", partido: "Esteban Echeverría", urlOficial: "https://www.estebanecheverria.gob.ar/", poblacion: 359592, superficieKm2: 120, densidad: 2996.6, region: Region.CONURBANO_SUR, esPiloto: false },
  { id: "060260", nombre: "Exaltación de la Cruz", partido: "Exaltación de la Cruz", urlOficial: "https://www.exaltaciondelacruz.com.ar/", poblacion: 34614, superficieKm2: 662, densidad: 52.3, region: Region.INTERIOR, esPiloto: false },
  { id: "060266", nombre: "Ezeiza", partido: "Ezeiza", urlOficial: "https://www.ezeiza.gob.ar/ezeiza_municipio_principal.php", poblacion: 199189, superficieKm2: 223, densidad: 893.2, region: Region.CONURBANO_SUR, esPiloto: false },
  { id: "060270", nombre: "Florencio Varela", partido: "Florencio Varela", urlOficial: "https://www.varela.gob.ar/default.aspx?", poblacion: 500530, superficieKm2: 190, densidad: 2634.4, region: Region.CONURBANO_SUR, esPiloto: false },
  { id: "060274", nombre: "Florentino Ameghino", partido: "Florentino Ameghino", urlOficial: "https://ameghino.gob.ar/", poblacion: 9475, superficieKm2: 1825, densidad: 5.2, region: Region.INTERIOR, esPiloto: false },
  { id: "060277", nombre: "General Alvarado", partido: "General Alvarado", urlOficial: null, poblacion: 47917, superficieKm2: 1677, densidad: 28.6, region: Region.COSTA_ATLANTICA, esPiloto: false },
  { id: "060280", nombre: "General Alvear", partido: "General Alvear", urlOficial: null, poblacion: 11136, superficieKm2: 3432, densidad: 3.2, region: Region.INTERIOR, esPiloto: false },
  { id: "060287", nombre: "General Arenales", partido: "General Arenales", urlOficial: "https://www.generalarenales.gob.ar/", poblacion: 15218, superficieKm2: 1540, densidad: 9.9, region: Region.INTERIOR, esPiloto: false },
  { id: "060294", nombre: "General Belgrano", partido: "General Belgrano", urlOficial: "https://gestion.generalbelgrano.gob.ar/", poblacion: 19062, superficieKm2: 1850, densidad: 10.3, region: Region.INTERIOR, esPiloto: false },
  { id: "060301", nombre: "General Guido", partido: "General Guido", urlOficial: "https://www.generalguido.gob.ar/", poblacion: 2870, superficieKm2: 2720, densidad: 1.1, region: Region.INTERIOR, esPiloto: false },
  { id: "060308", nombre: "General Juan Madariaga", partido: "General Juan Madariaga", urlOficial: "https://www.madariaga.gob.ar/", poblacion: 21833, superficieKm2: 2963, densidad: 7.4, region: Region.INTERIOR, esPiloto: false },
  { id: "060315", nombre: "General La Madrid", partido: "General La Madrid", urlOficial: "https://www.lamadrid.gob.ar/", poblacion: 11640, superficieKm2: 4725, densidad: 2.5, region: Region.INTERIOR, esPiloto: false },
  { id: "060322", nombre: "General Las Heras", partido: "General Las Heras", urlOficial: "https://lasheras.gob.ar/", poblacion: 17537, superficieKm2: 760, densidad: 23.1, region: Region.INTERIOR, esPiloto: false },
  { id: "060329", nombre: "General Lavalle", partido: "General Lavalle", urlOficial: "https://www.generallavalle.gob.ar/", poblacion: 3772, superficieKm2: 2639, densidad: 1.4, region: Region.COSTA_ATLANTICA, esPiloto: false },
  { id: "060336", nombre: "General Paz", partido: "General Paz", urlOficial: "https://www.generalpaz.gob.ar/", poblacion: 12766, superficieKm2: 1240, densidad: 10.3, region: Region.INTERIOR, esPiloto: false },
  { id: "060343", nombre: "General Pinto", partido: "General Pinto", urlOficial: "https://www.pinto.gob.ar/", poblacion: 11858, superficieKm2: 2523, densidad: 4.7, region: Region.INTERIOR, esPiloto: false },
  { id: "060351", nombre: "General Rodríguez", partido: "General Rodríguez", urlOficial: "https://generalrodriguez.gob.ar/inicio", poblacion: 99705, superficieKm2: 360, densidad: 277.0, region: Region.CONURBANO_OESTE, esPiloto: false },
  { id: "060364", nombre: "General San Martín", partido: "General San Martín", urlOficial: null, poblacion: 434120, superficieKm2: 56, densidad: 7752.1, region: Region.CONURBANO_NORTE, esPiloto: false },
  { id: "060371", nombre: "General Viamonte", partido: "General Viamonte", urlOficial: "https://www.generalviamonte.gob.ar/", poblacion: 19231, superficieKm2: 2150, densidad: 8.9, region: Region.INTERIOR, esPiloto: false },
  { id: "060378", nombre: "General Villegas", partido: "General Villegas", urlOficial: "https://villegas.gob.ar/", poblacion: 33270, superficieKm2: 7230, densidad: 4.6, region: Region.INTERIOR, esPiloto: false },
  { id: "060385", nombre: "Guaminí", partido: "Guaminí", urlOficial: "https://www.guamini.gob.ar/", poblacion: 12325, superficieKm2: 4830, densidad: 2.6, region: Region.INTERIOR, esPiloto: false },
  { id: "060392", nombre: "Hipólito Yrigoyen", partido: "Hipólito Yrigoyen", urlOficial: "https://www.hipolitoyrigoyen.gob.ar/", poblacion: 9963, superficieKm2: 1663, densidad: 6.0, region: Region.INTERIOR, esPiloto: false },
  { id: "060399", nombre: "Hurlingham", partido: "Hurlingham", urlOficial: "https://www.hurlingham.gob.ar/", poblacion: 193745, superficieKm2: 36, densidad: 5381.8, region: Region.CONURBANO_OESTE, esPiloto: false },
  { id: "060406", nombre: "Ituzaingó", partido: "Ituzaingó", urlOficial: "https://www.ituzaingo.gob.ar/", poblacion: 181440, superficieKm2: 39, densidad: 4652.3, region: Region.CONURBANO_OESTE, esPiloto: false },
  { id: "060408", nombre: "José C. Paz", partido: "José C. Paz", urlOficial: "https://josecpaz.com.ar/", poblacion: 305025, superficieKm2: 50, densidad: 6100.5, region: Region.CONURBANO_NORTE, esPiloto: false },
  { id: "060410", nombre: "Junín", partido: "Junín", urlOficial: "https://www.junin.gob.ar/", poblacion: 97514, superficieKm2: 2260, densidad: 43.1, region: Region.INTERIOR, esPiloto: false },
  { id: "060412", nombre: "La Costa", partido: "La Costa", urlOficial: "https://lacosta.gob.ar/", poblacion: 107917, superficieKm2: 226, densidad: 477.5, region: Region.COSTA_ATLANTICA, esPiloto: false },
  { id: "060420", nombre: "Laprida", partido: "Laprida", urlOficial: "https://www.laprida.gov.ar/", poblacion: 11078, superficieKm2: 3440, densidad: 3.2, region: Region.INTERIOR, esPiloto: false },
  { id: "060427", nombre: "Las Flores", partido: "Las Flores", urlOficial: "https://lasflores.gob.ar/", poblacion: 25055, superficieKm2: 3350, densidad: 7.5, region: Region.INTERIOR, esPiloto: false },
  { id: "060434", nombre: "Lanús", partido: "Lanús", urlOficial: "https://www.lanus.gob.ar/", poblacion: 471895, superficieKm2: 45, densidad: 10486.6, region: Region.CONURBANO_SUR, esPiloto: false },
  { id: "060448", nombre: "Lezama", partido: "Lezama", urlOficial: "https://lezama.gov.ar/", poblacion: 5157, superficieKm2: 2600, densidad: 2.0, region: Region.INTERIOR, esPiloto: false },
  { id: "060455", nombre: "Leandro N. Alem", partido: "Leandro N. Alem", urlOficial: "https://leandronalem.gob.ar/", poblacion: 17434, superficieKm2: 1640, densidad: 10.6, region: Region.INTERIOR, esPiloto: false },
  { id: "060462", nombre: "Lincoln", partido: "Lincoln", urlOficial: "https://www.lincoln.gob.ar/", poblacion: 43576, superficieKm2: 5790, densidad: 7.5, region: Region.INTERIOR, esPiloto: false },
  { id: "060469", nombre: "Lobos", partido: "Lobos", urlOficial: "https://www.lobos.gob.ar/", poblacion: 40701, superficieKm2: 1740, densidad: 23.4, region: Region.INTERIOR, esPiloto: false },
  { id: "060483", nombre: "Lomas de Zamora", partido: "Lomas de Zamora", urlOficial: "https://lomasdezamora.com.ar/", poblacion: 635783, superficieKm2: 89, densidad: 7143.6, region: Region.CONURBANO_SUR, esPiloto: false },
  { id: "060497", nombre: "Magdalena", partido: "Magdalena", urlOficial: "https://magdalena.gob.ar/", poblacion: 19746, superficieKm2: 1863, densidad: 10.6, region: Region.INTERIOR, esPiloto: false },
  { id: "060498", nombre: "Maipú", partido: "Maipú", urlOficial: "https://www.maipu.gob.ar/", poblacion: 10625, superficieKm2: 2580, densidad: 4.1, region: Region.INTERIOR, esPiloto: false },
  { id: "060505", nombre: "Malvinas Argentinas", partido: "Malvinas Argentinas", urlOficial: null, poblacion: 355533, superficieKm2: 63, densidad: 5643.4, region: Region.CONURBANO_NORTE, esPiloto: false },
  { id: "060511", nombre: "Mar Chiquita", partido: "Mar Chiquita", urlOficial: "https://www.marchiquita.gob.ar/", poblacion: 26828, superficieKm2: 3116, densidad: 8.6, region: Region.COSTA_ATLANTICA, esPiloto: false },
  { id: "060515", nombre: "Marcos Paz", partido: "Marcos Paz", urlOficial: "https://www.marcospaz.gov.ar/", poblacion: 67589, superficieKm2: 470, densidad: 143.8, region: Region.CONURBANO_OESTE, esPiloto: false },
  { id: "060519", nombre: "Mercedes", partido: "Mercedes", urlOficial: null, poblacion: 69340, superficieKm2: 1050, densidad: 66.0, region: Region.INTERIOR, esPiloto: false },
  { id: "060525", nombre: "Merlo", partido: "Merlo", urlOficial: "https://www.merlo.gob.ar/", poblacion: 587442, superficieKm2: 170, densidad: 3455.5, region: Region.CONURBANO_OESTE, esPiloto: false },
  { id: "060528", nombre: "Monte", partido: "Monte", urlOficial: "https://monte.gob.ar/", poblacion: 23594, superficieKm2: 1880, densidad: 12.5, region: Region.INTERIOR, esPiloto: false },
  { id: "060531", nombre: "Monte Hermoso", partido: "Monte Hermoso", urlOficial: "https://montehermoso.gov.ar/sitio/", poblacion: 8096, superficieKm2: 229, densidad: 35.4, region: Region.COSTA_ATLANTICA, esPiloto: false },
  { id: "060535", nombre: "Moreno", partido: "Moreno", urlOficial: "https://www.moreno.gob.ar/", poblacion: 556741, superficieKm2: 186, densidad: 2993.2, region: Region.CONURBANO_OESTE, esPiloto: false },
  { id: "060539", nombre: "Morón", partido: "Morón", urlOficial: "https://www.moron.gob.ar/", poblacion: 342335, superficieKm2: 56, densidad: 6113.1, region: Region.CONURBANO_OESTE, esPiloto: false },
  { id: "060546", nombre: "Navarro", partido: "Navarro", urlOficial: "https://navarro.gob.ar/", poblacion: 19429, superficieKm2: 1630, densidad: 11.9, region: Region.INTERIOR, esPiloto: false },
  { id: "060560", nombre: "9 de Julio", partido: "9 de Julio", urlOficial: "https://www.9dejulio.gob.ar/", poblacion: 49876, superficieKm2: 4230, densidad: 11.8, region: Region.INTERIOR, esPiloto: false },
  { id: "060574", nombre: "Olavarría", partido: "Olavarría", urlOficial: "https://www.olavarria.gov.ar/", poblacion: 118882, superficieKm2: 7715, densidad: 15.4, region: Region.INTERIOR, esPiloto: false },
  { id: "060581", nombre: "Patagones", partido: "Patagones", urlOficial: "https://patagones.gob.ar/", poblacion: 31571, superficieKm2: 13597, densidad: 2.3, region: Region.INTERIOR, esPiloto: false },
  { id: "060588", nombre: "Pehuajó", partido: "Pehuajó", urlOficial: "https://www.pehuajo.gob.ar/", poblacion: 42094, superficieKm2: 4560, densidad: 9.2, region: Region.INTERIOR, esPiloto: false },
  { id: "060595", nombre: "Pellegrini", partido: "Pellegrini", urlOficial: "https://www.pellegrini.gov.ar/", poblacion: 6165, superficieKm2: 1895, densidad: 3.3, region: Region.INTERIOR, esPiloto: false },
  { id: "060602", nombre: "Pergamino", partido: "Pergamino", urlOficial: "https://pergamino.ar/", poblacion: 109065, superficieKm2: 2950, densidad: 37.0, region: Region.INTERIOR, esPiloto: false },
  { id: "060609", nombre: "Pila", partido: "Pila", urlOficial: "https://pila.gob.ar/", poblacion: 3772, superficieKm2: 3452, densidad: 1.1, region: Region.INTERIOR, esPiloto: false },
  { id: "060616", nombre: "Pilar", partido: "Pilar", urlOficial: "https://pilar.gov.ar/", poblacion: 366018, superficieKm2: 352, densidad: 1039.8, region: Region.CONURBANO_NORTE, esPiloto: false },
  { id: "060623", nombre: "Pinamar", partido: "Pinamar", urlOficial: "https://pinamar.gob.ar/", poblacion: 48487, superficieKm2: 63, densidad: 769.6, region: Region.COSTA_ATLANTICA, esPiloto: false },
  { id: "060630", nombre: "Presidente Perón", partido: "Presidente Perón", urlOficial: "https://presidenteperon.gob.ar/", poblacion: 102440, superficieKm2: 121, densidad: 846.6, region: Region.CONURBANO_SUR, esPiloto: false },
  { id: "060631", nombre: "Puan", partido: "Puan", urlOficial: "https://www.puan.gob.ar/", poblacion: 15499, superficieKm2: 6385, densidad: 2.4, region: Region.INTERIOR, esPiloto: false },
  { id: "060632", nombre: "Punta Indio", partido: "Punta Indio", urlOficial: "https://puntaindio.gov.ar/", poblacion: 10687, superficieKm2: 1627, densidad: 6.6, region: Region.INTERIOR, esPiloto: false },
  { id: "060638", nombre: "Quilmes", partido: "Quilmes", urlOficial: "https://www.quilmes.gob.ar/", poblacion: 587376, superficieKm2: 94, densidad: 6248.7, region: Region.CONURBANO_SUR, esPiloto: false },
  { id: "060644", nombre: "Ramallo", partido: "Ramallo", urlOficial: "https://www.ramallo.gob.ar/", poblacion: 36014, superficieKm2: 1040, densidad: 34.6, region: Region.INTERIOR, esPiloto: false },
  { id: "060648", nombre: "Rauch", partido: "Rauch", urlOficial: "https://www.rauch.com.ar/", poblacion: 16240, superficieKm2: 4300, densidad: 3.8, region: Region.INTERIOR, esPiloto: false },
  { id: "060651", nombre: "Rivadavia", partido: "Rivadavia", urlOficial: "https://rivadavia.gob.ar/", poblacion: 17143, superficieKm2: 3880, densidad: 4.4, region: Region.INTERIOR, esPiloto: false },
  { id: "060655", nombre: "Rojas", partido: "Rojas", urlOficial: "https://www.rojas.gob.ar/", poblacion: 24563, superficieKm2: 2050, densidad: 12.0, region: Region.INTERIOR, esPiloto: false },
  { id: "060658", nombre: "Roque Pérez", partido: "Roque Pérez", urlOficial: "https://www.roqueperez.gob.ar/", poblacion: 13636, superficieKm2: 1550, densidad: 8.8, region: Region.INTERIOR, esPiloto: false },
  { id: "060665", nombre: "Saavedra", partido: "Saavedra", urlOficial: "https://saavedra.com.ar/", poblacion: 21913, superficieKm2: 3500, densidad: 6.3, region: Region.INTERIOR, esPiloto: false },
  { id: "060672", nombre: "Saladillo", partido: "Saladillo", urlOficial: "https://www.saladillo.gob.ar/", poblacion: 33159, superficieKm2: 2736, densidad: 12.1, region: Region.INTERIOR, esPiloto: false },
  { id: "060679", nombre: "Salliqueló", partido: "Salliqueló", urlOficial: "https://www.salliquelo.gob.ar/", poblacion: 9305, superficieKm2: 768, densidad: 12.1, region: Region.INTERIOR, esPiloto: false },
  { id: "060686", nombre: "Salto", partido: "Salto", urlOficial: "https://salto.gob.ar/", poblacion: 34479, superficieKm2: 1630, densidad: 21.2, region: Region.INTERIOR, esPiloto: false },
  { id: "060693", nombre: "San Andrés de Giles", partido: "San Andrés de Giles", urlOficial: "https://www.sanandresdegiles.gob.ar/", poblacion: 26000, superficieKm2: 1135, densidad: 22.9, region: Region.INTERIOR, esPiloto: false },
  { id: "060700", nombre: "San Antonio de Areco", partido: "San Antonio de Areco", urlOficial: "https://areco.ar/", poblacion: 24892, superficieKm2: 857, densidad: 29.0, region: Region.INTERIOR, esPiloto: false },
  { id: "060707", nombre: "San Cayetano", partido: "San Cayetano", urlOficial: "https://sancayetano.gob.ar/", poblacion: 8875, superficieKm2: 3060, densidad: 2.9, region: Region.INTERIOR, esPiloto: false },
  { id: "060714", nombre: "San Fernando", partido: "San Fernando", urlOficial: "https://www.sanfernando.gob.ar/", poblacion: 177068, superficieKm2: 924, densidad: 191.6, region: Region.CONURBANO_NORTE, esPiloto: false },
  { id: "060721", nombre: "San Nicolás", partido: "San Nicolás", urlOficial: null, poblacion: 149652, superficieKm2: 680, densidad: 220.1, region: Region.INTERIOR, esPiloto: false },
  { id: "060728", nombre: "San Pedro", partido: "San Pedro", urlOficial: "https://www.sanpedro.net.ar/", poblacion: 63522, superficieKm2: 1321, densidad: 48.1, region: Region.INTERIOR, esPiloto: false },
  { id: "060742", nombre: "San Vicente", partido: "San Vicente", urlOficial: "https://www.sanvicente.gob.ar/", poblacion: 73514, superficieKm2: 656, densidad: 112.1, region: Region.CONURBANO_SUR, esPiloto: false },
  { id: "060749", nombre: "Suipacha", partido: "Suipacha", urlOficial: "https://suipacha.gob.ar/", poblacion: 11041, superficieKm2: 950, densidad: 11.6, region: Region.INTERIOR, esPiloto: false },
  { id: "060756", nombre: "San Miguel", partido: "San Miguel", urlOficial: null, poblacion: 320557, superficieKm2: 83, densidad: 3861.5, region: Region.CONURBANO_NORTE, esPiloto: false },
  { id: "060760", nombre: "Tapalqué", partido: "Tapalqué", urlOficial: null, poblacion: 10736, superficieKm2: 4172, densidad: 2.6, region: Region.INTERIOR, esPiloto: false },
  { id: "060763", nombre: "Tigre", partido: "Tigre", urlOficial: null, poblacion: 429850, superficieKm2: 360, densidad: 1194.0, region: Region.CONURBANO_NORTE, esPiloto: false },
  { id: "060766", nombre: "Tordillo", partido: "Tordillo", urlOficial: null, poblacion: 1962, superficieKm2: 1340, densidad: 1.5, region: Region.INTERIOR, esPiloto: false },
  { id: "060770", nombre: "Tornquist", partido: "Tornquist", urlOficial: "https://www.tornquist.gob.ar/", poblacion: 14118, superficieKm2: 4183, densidad: 3.4, region: Region.INTERIOR, esPiloto: false },
  { id: "060778", nombre: "Trenque Lauquen", partido: "Trenque Lauquen", urlOficial: "https://www.trenquelauquen.gov.ar/", poblacion: 47757, superficieKm2: 5500, densidad: 8.7, region: Region.INTERIOR, esPiloto: false },
  { id: "060784", nombre: "Tres Arroyos", partido: "Tres Arroyos", urlOficial: "https://www.tresarroyos.gov.ar/", poblacion: 59062, superficieKm2: 5861, densidad: 10.1, region: Region.INTERIOR, esPiloto: false },
  { id: "060795", nombre: "Tres de Febrero", partido: "Tres de Febrero", urlOficial: "https://www.tresdefebrero.gov.ar/", poblacion: 353557, superficieKm2: 46, densidad: 7686.0, region: Region.CONURBANO_OESTE, esPiloto: false },
  { id: "060798", nombre: "Tres Lomas", partido: "Tres Lomas", urlOficial: "https://www.treslomas.gob.ar/", poblacion: 8709, superficieKm2: 1250, densidad: 7.0, region: Region.INTERIOR, esPiloto: false },
  { id: "060805", nombre: "25 de Mayo", partido: "25 de Mayo", urlOficial: "https://25demayo.gob.ar/", poblacion: 38875, superficieKm2: 4770, densidad: 8.1, region: Region.INTERIOR, esPiloto: false },
  { id: "060812", nombre: "Villa Gesell", partido: "Villa Gesell", urlOficial: "https://www.gesell.gob.ar/", poblacion: 42741, superficieKm2: 285, densidad: 150.0, region: Region.COSTA_ATLANTICA, esPiloto: false },
  { id: "060819", nombre: "Villarino", partido: "Villarino", urlOficial: "https://www.villarino.gob.ar/", poblacion: 32324, superficieKm2: 11400, densidad: 2.8, region: Region.INTERIOR, esPiloto: false },
  { id: "060826", nombre: "La Matanza", partido: "La Matanza", urlOficial: "https://www.lamatanza.gov.ar/", poblacion: 1837774, superficieKm2: 325, densidad: 5654.7, region: Region.CONURBANO_OESTE, esPiloto: false },
  { id: "060547", nombre: "Bolívar", partido: "Bolívar", urlOficial: "https://www.bolivar.gob.ar/", poblacion: 36280, superficieKm2: 5027, densidad: 7.2, region: Region.INTERIOR, esPiloto: false },
];

/** Los 13 municipios piloto */
export const MUNICIPIOS_PILOTO = MUNICIPIOS.filter((m) => m.esPiloto);

/** Buscar municipio por ID */
export function getMunicipioById(id: string): Municipio | undefined {
  return MUNICIPIOS.find((m) => m.id === id);
}

/** Buscar municipios por nombre (búsqueda parcial, case-insensitive) */
export function searchMunicipios(query: string): Municipio[] {
  const q = query.toLowerCase();
  return MUNICIPIOS.filter(
    (m) =>
      m.nombre.toLowerCase().includes(q) ||
      m.partido.toLowerCase().includes(q)
  );
}
