// Types
export {
  type Municipio,
  Region,
  type Source,
  SourceType,
  SourceStatus,
  type Document,
  DocumentCategory,
  DocumentFormat,
  type TransparencyScore,
  type DimensionScore,
  type ScoreEvidence,
  ScoringDimension,
  ScoringCategory,
  type CategoryConfig,
  SCORING_CATEGORIES,
  type WeightedTotalResult,
  computeWeightedTotal,
  type FiscalIndicator,
  type FiscalIndicatorSourced,
  type FiscalPrimaryField,
  FISCAL_PRIMARY_FIELDS,
  flattenFiscalIndicator,
  type DocumentAudit,
  type AccessibilityAudit,
  type PilotAuditEntry,
  type PilotAuditData,
  type NormaTipo,
  type Norma,
  type NormativaData,
  type ComprasData,
  type SourcedValue,
  type DataPointSource,
  type DataPointConfidence,
  ConfidenceLevel,
  type DataPoint,
  type DataGap,
  DataGapType,
  DATA_GAP_TYPE_META,
  type CasoTestigoParams,
  CASOS_TESTIGO_DEFAULT,
  type PresionImpositivaData,
  type PresionImpositivaRankingEntry,
  type PresionImpositivaStats,
  type Contratacion,
  type ContratacionEstado,
  type ContratacionesAggregate,
  type RefreshManifest,
  type MonthlyRefreshRun,
  type GlobalRefreshManifest,
  type AcreedorSaldo,
  type StockDeudaSnapshot,
} from "./types/index";

// Constants
export {
  MUNICIPIOS,
  MUNICIPIOS_PILOTO,
  getMunicipioById,
  searchMunicipios,
  FISCAL_DOCUMENT_CATEGORIES,
  ACTIVE_DIMENSIONS,
  DOCUMENT_CATEGORY_LABELS,
  SCORING_DIMENSION_LABELS,
  TRANSPARENCY_WEIGHTS,
  TOTAL_WEIGHT,
  type TransparencyWeight,
  FISCAL_EXPANDED_WEIGHTS,
  SourceLayer,
  SOURCE_LAYER_META,
  type SourceLayerMeta,
  KNOWN_ORGANISMS,
  type KnownOrganism,
  getOrganismById,
  DataField,
  DATA_FIELD_META,
  type DataFieldMeta,
} from "./constants/index";
